name:                gmcheck
version:             0.0.3.0
github:              "yuuri/gmcheck"
license:             BSD3
author:              "Yulia Gorshkova"
maintainer:          "yuliosity@gmail.com"
copyright:           "2020-2025 Yulia Gorshkova"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on BitBucket at <https://bitbucket.org/yuuri/gmcheck#readme>

dependencies:
- base >= 4.7 && < 5
- blaze-html
- blaze-markup
- bytestring
- containers
- directory
- filepath
- keycode
- megaparsec
- microlens-platform
- parser-combinators
- text
- transformers
- HsYAML

library:
  default-extensions:
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
  source-dirs: src
  ghc-options: [-W]

executables:
  gmcheck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative
    - gmcheck

tests:
  gmcheck-parser-test:
    main:                Main.hs
    source-dirs:         src/Language/GML/Parser/test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-megaparsec
    - gmcheck
    default-extensions:
    - OverloadedStrings
