name: CI

on:
  push:
    branches:
      # PRs can only use caches from their target branch. We therefore need to
      # make sure we run on 'master' too.
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml

  fourmolu:
    needs: pre-commit
    uses: ./.github/workflows/fourmolu.yaml

  hlint:
    needs: fourmolu
    uses: ./.github/workflows/hlint.yaml

  build-and-test:
    needs: hlint
    uses: ./.github/workflows/build-and-test.yaml
