name: Examples
on: push
jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: nixbuild/nix-quick-install-action@v28
      - run: nix-build --version
      - run: nix-shell -p hpack --command hpack
      - run: nix-build
